# 1. What does OOP stand for?
a. Object Oriented Programming b. Open Object Programming c. Object Oriented Process d. Ordered Object Programming

Answer :- Object Oriented Programming

# 2. Which of the following is NOT a pillar of OOPS?
a. Encapsulation b. Inheritance c. Compilation d. Polymorphism

Answer :- Compilation

# 3. Encapsulation mainly helps in?
a. Code reuse b. Data hiding c. Multiple inheritance d. Faster execution

Answer :- Data hiding

# 4. Inheritance allows?
a. Creating new classes from existing ones b. Hiding data c. Multiple methods with same name d. None

Answer :- Creating new classes from existing ones

# 5. Polymorphism means?
a. Many forms b. Single form c. Code hiding d. Data security

Answer :- Many forms

# 6. NumPy arrays are called?
a. Lists b. Tuples c. ndarray d. Series

Answer :- ndarray

# 7. Which library is used for numerical computing in Python?
a. Pandas b. Matplotlib c. NumPy d. Seaborn

Answer :- NumPy

# 8. Which function creates an array of zeros?
a. np.zero() b. np.zeros() c. np.empty() d. np.null()

Answer :- np.zeros()

# 9. np.ones((2,3)) creates?
a. 2 elements b. 3 elements c. 2x3 matrix of ones d. 3x2 matrix of zeros

Answer :- 2x3 matrix of ones

# 10. Which function creates an identity matrix?
a. np.eye() b. np.identity() c. Both A and B d. np.diagonal()

Answer :- Both A and B

# 11. np.eye(3) returns?
a. 3x3 zero matrix b. 3x3 identity matrix c. Diagonal matrix d. Random matrix

Answer :- 3x3 identity matrix

# 12. np.full((2,2),5) produces?
a. Zeros b. Ones c. Random values d. All elements as 5

Answer :- All elements as 5

# 13. Which function generates random values?
a. np.random() b. np.rand() c. np.random.random() d. np.randomize()

Answer :- np.random.random()

# 14. Pandas is mainly used for?
a. Numerical arrays b. Data analysis c. Plotting d. Game development

Answer :- Data analysis

# 15. A Pandas DataFrame is?
a. 1D b. 2D c. 3D d. Scalar

Answer :- 2D

# 16. Pandas Series is?
a. 2D b. 3D c. 1D labeled array d. Matrix

Answer :- 1D labeled array

# 17. df.head() shows?
a. Last rows b. Random rows c. First 5 rows d. All rows

Answer :- First 5 rows

# 18. df.tail(3) returns?
a. First 3 rows b. Last 3 rows c. Random 3 rows d. Middle rows

Answer :- Last 3 rows

# 19. df.info() is used to?
a. Show statistics b. Check nulls & datatypes c. Sort data d. Plot data

Answer :- Check nulls & datatypes

# 20. df.sample() does what?
a. Sorts data b. Selects random rows c. Removes nulls d. Adds rows

Answer :- Selects random rows

# 21. df.describe() gives?
a. Structure b. Summary statistics c. Null count d. Duplicates
Answer :- Summary statistics

# 22. Which function removes null values?
a. fillna() b. dropna() c. isnull() d. notnull()

Answer :- dropna()

# 23. To replace null values we use?
a. dropna() b. replace() c. fillna() d. remove()

Answer :- fillna()

# 24. Which function finds duplicate rows?
a. df.duplicated() b. df.repeat() c. df.copy() d. df.clone()

answer :- df.duplicated()

# 25. To remove duplicates we use?
a. df.remove() b. df.drop_duplicates() c. df.clean() d. df.unique()

Answer :- df.drop_duplicates()

# 26. Write Python code to create a NumPy array of zeros with shape (3,4).

In [1]:
import numpy as np
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 27. Write Python code to create a Pandas DataFrame with two columns: Name and Age.

In [2]:
import pandas as pd
df = pd.DataFrame({"Name" : ["Alice", "Tom", "Jake"], "Age" : [23, 24, 23]})
df

    Name  Age
0  Alice   23
1    Tom   24
2   Jake   23

# 28. Download the dataset and load in a dataframe
Link -> https://www.kaggle.com/datasets/yasserh/titanic-dataset

In [3]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 29. Show top 10 rows, bottom 6 rows and random 8 rows

In [4]:
# Top 10 rows
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [5]:
# bottom 6 rows
df.tail(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

In [6]:
# Random 8 rows
df.sample(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
398,399,0,2,"Pain, Dr. Alfred",male,23.0,0,0,244278,10.5000,NaN,S
811,812,0,3,"Lester, Mr. James",male,39.0,0,0,A/4 48871,24.1500,NaN,S
281,282,0,3,"Olsson, Mr. Nils Johan Goransson",male,28.0,0,0,347464,7.8542,NaN,S
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S
112,113,0,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,NaN,S
228,229,0,2,"Fahlstrom, Mr. Arne Jonas",male,18.0,0,0,236171,13.0000,NaN,S
143,144,0,3,"Burke, Mr. Jeremiah",male,19.0,0,0,365222,6.7500,NaN,Q
452,453,0,1,"Foreman, Mr. Benjamin Laventall",male,30.0,0,0,113051,27.7500,C111,C

# 30. Print the information and statistical description of the data

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 31. Handle null values and duplicates

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [12]:
df["Cabin"] = df["Cabin"].fillna(df["Cabin"].mode()[0])

In [13]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [14]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64